on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: flaskmlapp.azurecr.io
        username: ${{ secrets.acr_flaskmlapp_username }}
        password: ${{ secrets.acr_flaskmlapp_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t flaskmlapp.azurecr.io/flaskmlaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push flaskmlapp.azurecr.io/flaskmlaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_flaskmlaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep flaskmlaksb103 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace flaskmlaksb103`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: flaskmlaksb103
        container-registry-url: flaskmlapp.azurecr.io
        container-registry-username: ${{ secrets.acr_flaskmlapp_username }}
        container-registry-password: ${{ secrets.acr_flaskmlapp_password }}
        secret-name: flaskmlaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: flaskmlaksb103
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          flaskmlapp.azurecr.io/flaskmlaks:${{ github.sha }}
        imagepullsecrets: |
          flaskmlaksdockerauth
